//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> FechaFacturacion { get; set; }
        public Nullable<int> FK_PlanCobro { get; set; }
        public Nullable<int> FK_Propiedad { get; set; }
        public string Tarjeta { get; set; }
        public Nullable<int> FK_Tarjeta { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual PlanCobro PlanCobro { get; set; }
        public virtual Propiedad Propiedad { get; set; }
        public virtual Tarjeta Tarjeta1 { get; set; }
    }
}
