//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificacionUsuario
    {
        public int IdUsuario { get; set; }
        public int IdNotificacion { get; set; }
        public Nullable<bool> Leida { get; set; }
    
        public virtual Notificacion Notificacion { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
