//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanxRubro
    {
        public int FK_Rubro { get; set; }
        public int FK_Plan { get; set; }
    
        public virtual PlanCobro PlanCobro { get; set; }
        public virtual RubroCobro RubroCobro { get; set; }
    }
}
